/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Tabelas.TabelaMedicos;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.bean.AgendaConsulta;
import model.conexao.Conexao;
import model.dao.AgendaDao;

/**
 *
 * @author Vaio
 */
public class Agenda extends javax.swing.JFrame {

    Conexao con = new Conexao();
    AgendaConsulta agenda= new AgendaConsulta();
    AgendaConsulta agen = new AgendaConsulta();
    AgendaDao daoAgenda = new AgendaDao();
    
    String status;
    String dtHoje;
    
    public Agenda() {
        initComponents();
        
        Calendar data = Calendar.getInstance();
        Date d = data.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.format(d);
     
        dtHoje = dateFormat.format(d);
        status = "Aberto";
        
        preencherTabela("select * from agendamento inner join paciente on agendamento.Id_paciente = paciente.Id_paciente inner join medico on agendamento.Id_medico = medico.Id_medico where agenda_data = '"+dtHoje+"' and agenda_status = '"+status+"' order by agenda_turno;");
        
    }
    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Nome","Turno","Data","Status","Medico"};
        con.getConnection();
        con.executaSql(Sql);
        try {
            con.rs.first();
            do{                    
                  dados.add(new Object[]{con.rs.getInt("agendamento.agenda_cod"),con.rs.getString("paciente.nome"),
                      con.rs.getString("agenda_turno"),con.rs.getString("agenda_data"),con.rs.getString("agenda_status"),
                      con.rs.getString("medico.nome")});
                } while (con.rs.next());
        } catch (SQLException e) {
       }
         TabelaMedicos tabela = new TabelaMedicos(dados, colunas);
         
         tabelaAgenda.setModel(tabela);
         tabelaAgenda.getColumnModel().getColumn(0).setPreferredWidth(30);
         tabelaAgenda.getColumnModel().getColumn(0).setResizable(true);
         tabelaAgenda.getColumnModel().getColumn(1).setPreferredWidth(220);
         tabelaAgenda.getColumnModel().getColumn(1).setResizable(true);
         tabelaAgenda.getColumnModel().getColumn(2).setPreferredWidth(80);
         tabelaAgenda.getColumnModel().getColumn(2).setResizable(true);
         tabelaAgenda.getColumnModel().getColumn(3).setPreferredWidth(85);
         tabelaAgenda.getColumnModel().getColumn(3).setResizable(true);
         tabelaAgenda.getColumnModel().getColumn(4).setPreferredWidth(115);
         tabelaAgenda.getColumnModel().getColumn(4).setResizable(true);
         tabelaAgenda.getColumnModel().getColumn(5).setPreferredWidth(211);
         tabelaAgenda.getColumnModel().getColumn(5).setResizable(true);
         tabelaAgenda.getTableHeader().setReorderingAllowed(true);
         tabelaAgenda.setAutoResizeMode(tabelaAgenda.AUTO_RESIZE_OFF);
         tabelaAgenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         con.desconecta();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAgenda = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAgendamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaAgenda);

        jLabel2.setText("Consultas Marcadas");

        btnAgendamento.setText("Atender Agendamento");
        btnAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgendamento)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agenda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(931, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendamentoActionPerformed
       daoAgenda.Alterar(agen);
       preencherTabela("select * from agendamento inner join paciente on agendamento.Id_paciente = paciente.Id_paciente inner join medico on agendamento.Id_medico = medico.Id_medico where agenda_data = '"+dtHoje+"' and agenda_status = '"+status+"' order by agenda_turno;");

    }//GEN-LAST:event_btnAgendamentoActionPerformed

    private void tabelaAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAgendaMouseClicked
      String agenda_cod = ""+tabelaAgenda.getValueAt(tabelaAgenda.getSelectedRow(), 0);
     con.getConnection();
       con.executaSql("select * from agendamento where agenda_cod='"+agenda_cod+"'");
        try {
            con.rs.first();
            agen.setStatus("Em Atendimento");
            agen.setAgendaCod(con.rs.getInt("agenda_cod"));
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, "Erro no ao selecionar os dados"+ex);
        }
       con.desconecta();
    }//GEN-LAST:event_tabelaAgendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAgenda;
    // End of variables declaration//GEN-END:variables
}
