/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Tabelas.TabelaEnfermeiro;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.bean.Enfermeiro;
import model.conexao.Conexao;
import model.dao.EnfermeiroDao;

/**
 *
 * @author mathe
 */
public class CadEnfermeiros extends javax.swing.JFrame {
    
    Conexao con = new Conexao();
    Enfermeiro enfermeiro = new Enfermeiro();
    EnfermeiroDao control = new EnfermeiroDao();
    int flag =0;
    
    public CadEnfermeiros() {
        initComponents();
        con.getConnection();
         CamposInvisiveis();
         preencherTabelaEnfermeiros("select * from enfermeiro order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNomeEnfermeiro = new javax.swing.JTextField();
        txtEnfermeiroLogin = new javax.swing.JTextField();
        txtEnfermeirosenha = new javax.swing.JPasswordField();
        txtEnfermeiroConfirmarSenha = new javax.swing.JPasswordField();
        ComboTipo = new javax.swing.JComboBox<>();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnBuscarEnfermeiro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEnfermeiro = new javax.swing.JTable();
        txtID_enfermeiro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboEspecialização = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEnfermeiroEnde = new javax.swing.JTextField();
        txtEnfermeiroEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel3.setText("Login:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmar Senha:");

        jLabel6.setText("Perfil:");

        txtNomeEnfermeiro.setEnabled(false);

        txtEnfermeiroLogin.setEnabled(false);

        txtEnfermeirosenha.setEnabled(false);

        txtEnfermeiroConfirmarSenha.setEnabled(false);

        ComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------", "Enfermeiro", "Supervisor" }));
        ComboTipo.setEnabled(false);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_pacientes.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_37110.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alter_pacientes.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_paciente.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_pacientes.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnBuscarEnfermeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/procurar.png"))); // NOI18N
        btnBuscarEnfermeiro.setToolTipText("Buscar");
        btnBuscarEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEnfermeiroActionPerformed(evt);
            }
        });

        TabelaEnfermeiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaEnfermeiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEnfermeiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaEnfermeiro);

        jLabel7.setText("Especialização:");

        ComboEspecialização.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------", "Enfermagem Obstétrica", "Enfermagem em Estomaterapia com Ênfase em Feridas, Estomas e Incontinências", "Enfermagem em Saúde da Família", "Enfermagem Oncológica", "Enfermagem em Nefrologia", "Enfermagem do Trabalho", "Enfermagem em Cardiologia e Hemodinâmica", "Enfermagem em terapia intensiva" }));
        ComboEspecialização.setEnabled(false);

        jLabel8.setText("Email:");

        jLabel9.setText("Endereço:");

        txtEnfermeiroEnde.setEnabled(false);

        txtEnfermeiroEmail.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID_enfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtNomeEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(txtEnfermeiroEnde, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEnfermeiroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtEnfermeiroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarEnfermeiro))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(91, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboEspecialização, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnfermeirosenha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEnfermeiroConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtID_enfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeEnfermeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnfermeiroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnfermeiroEnde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnfermeiroEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnfermeirosenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnfermeiroConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboEspecialização, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEnfermeiro))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Cadastro de Enfermeiros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(949, 613));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            enfermeiro.setId_enfermeiro(Integer.parseInt(txtID_enfermeiro.getText()));
            control.Excluir(enfermeiro);
            LimparCampos();
            DesabiliarCampos();
            DesabilitarBotões();
            btnNovo.setEnabled(true);
            preencherTabelaEnfermeiros("select * from enfermeiro order by nome");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    
  
        
    private void btnBuscarEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEnfermeiroActionPerformed
      enfermeiro.setPesquisar(txtPesquisar.getText());
      Enfermeiro model = control.buscarEnfermeiro(enfermeiro);
      txtID_enfermeiro.setText((String.valueOf(model.getId_enfermeiro())));
      txtNomeEnfermeiro.setText(model.getNome());
      ComboEspecialização.setSelectedItem(model.getEspecialização());
      txtEnfermeiroLogin.setText(model.getLogin());
      txtEnfermeirosenha.setText(model.getSenha());
      txtEnfermeiroEmail.setText(model.getEmail());
      txtEnfermeiroEnde.setText(model.getEndereco());
      ComboTipo.setSelectedItem(model.getTipo());
      btnEditar.setEnabled(true);
      btnExcluir.setEnabled(true);
      txtPesquisar.setText("");
      preencherTabelaEnfermeiros("select * from enfermeiro order by nome like '%"+enfermeiro.getPesquisar()+"%'");
    }//GEN-LAST:event_btnBuscarEnfermeiroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNomeEnfermeiro.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Nome para cadastrar!");
            txtNomeEnfermeiro.requestFocus();
        }else if (txtEnfermeiroLogin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Login!");
            txtEnfermeiroLogin.requestFocus();
        }else if (txtEnfermeirosenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a Senha!");
            txtEnfermeirosenha.requestFocus();
        }else if (txtEnfermeiroEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Email!");
            txtEnfermeiroEmail.requestFocus();
        }else if (txtEnfermeiroEnde.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Endereço!");
            txtEnfermeiroEnde.requestFocus();
        }else if (txtEnfermeiroConfirmarSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Confirme sua senha!");
            txtEnfermeiroConfirmarSenha.requestFocus();
        }else if (txtEnfermeirosenha.getText().equals(txtEnfermeiroConfirmarSenha.getText())) {
            if(flag==1){
            enfermeiro.setNome(txtNomeEnfermeiro.getText());
            enfermeiro.setEspecialização((String)ComboEspecialização.getSelectedItem());
            enfermeiro.setLogin(txtEnfermeiroLogin.getText());
            enfermeiro.setSenha(txtEnfermeirosenha.getText());
            enfermeiro.setEmail(txtEnfermeiroEmail.getText());
            enfermeiro.setEndereco(txtEnfermeiroEnde.getText());
            enfermeiro.setTipo((String)ComboTipo.getSelectedItem());
            control.Salvar(enfermeiro);
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja fazer mais alguma coisa?");
            if (resposta == JOptionPane.NO_OPTION) { 
                dispose();
            }
            preencherTabelaEnfermeiros("select * from enfermeiro order by nome");
            LimparCampos();
            DesabilitarBotões();
            DesabiliarCampos();
            btnNovo.setEnabled(true);   
            }else{    
            enfermeiro.setId_enfermeiro((Integer.parseInt(txtID_enfermeiro.getText())));
            enfermeiro.setNome(txtNomeEnfermeiro.getText());
            enfermeiro.setEspecialização((String)ComboEspecialização.getSelectedItem());
            enfermeiro.setLogin(txtEnfermeiroLogin.getText());
            enfermeiro.setSenha(txtEnfermeirosenha.getText());
            enfermeiro.setEmail(txtEnfermeiroEmail.getText());
            enfermeiro.setEndereco(txtEnfermeiroEnde.getText());
            enfermeiro.setTipo((String)ComboTipo.getSelectedItem());
            control.Editar(enfermeiro);
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja fazer mais alguma coisa?");
            if (resposta == JOptionPane.NO_OPTION) { 
                dispose();
            }
            preencherTabelaEnfermeiros("select * from enfermeiro order by nome");
            LimparCampos();
            DesabilitarBotões();
            DesabiliarCampos();
            btnNovo.setEnabled(true);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "A senha que você digitou não confere!");
        }
        
            
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag=1;
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        HabilitarCampos();
        LimparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        flag=2;
        HabilitarCampos();
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Cancelar o Cadastro?");
            if (resposta == JOptionPane.YES_OPTION) { 
                LimparCampos();
                DesabiliarCampos();
                DesabilitarBotões();
                btnNovo.setEnabled(true);
            }
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void TabelaEnfermeiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEnfermeiroMouseClicked
       String nome = ""+TabelaEnfermeiro.getValueAt(TabelaEnfermeiro.getSelectedRow(), 1);
       con.getConnection();
       con.executaSql("select * from enfermeiro where nome='"+nome+"'");
        try {
            con.rs.first();
            txtID_enfermeiro.setText(String.valueOf(con.rs.getInt("ID_enfermeiro")));
            txtNomeEnfermeiro.setText(con.rs.getString("nome"));
            ComboEspecialização.setSelectedItem(con.rs.getString("especialização"));
            txtEnfermeiroLogin.setText(con.rs.getString("login"));
            txtEnfermeiroEmail.setText(con.rs.getString("email"));
            txtEnfermeiroEnde.setText(con.rs.getString("endereco"));
            ComboTipo.setSelectedItem(con.rs.getString("tipo"));
            txtEnfermeirosenha.setText(con.rs.getString("senha"));
            txtEnfermeiroConfirmarSenha.setText(con.rs.getString("senha"));
            
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, "Erro no ao selecionar os dados"+ex);
        }
       //con.desconecta();
        HabilitarBotões();
       
    }//GEN-LAST:event_TabelaEnfermeiroMouseClicked
    private void CamposInvisiveis(){
       txtID_enfermeiro.setVisible(false);
    }
    private void DesabilitarBotões(){
       btnSalvar.setEnabled(false);
       btnEditar.setEnabled(false);
       btnExcluir.setEnabled(false);
       btnCancelar.setEnabled(false);
    }
    private void DesabiliarCampos(){
       txtID_enfermeiro.setEditable(false);
       txtNomeEnfermeiro.setEnabled(false);
       ComboEspecialização.setEnabled(false);
       txtEnfermeiroLogin.setEnabled(false);
       txtEnfermeirosenha.setEnabled(false);
       txtEnfermeiroEnde.setEnabled(false);
       txtEnfermeiroEmail.setEnabled(false);    
       txtEnfermeiroConfirmarSenha.setEnabled(false);
       ComboTipo.setEnabled(false);
    }
    private void LimparCampos() {
       txtID_enfermeiro.setText("");
       txtNomeEnfermeiro.setText("");
       ComboEspecialização.setSelectedItem("");
       txtEnfermeiroLogin.setText("");
       txtEnfermeirosenha.setText("");
       txtEnfermeiroEnde.setText("");
       txtEnfermeiroEmail.setText("");    
       txtEnfermeiroConfirmarSenha.setText("");
       ComboTipo.setSelectedItem("");
    }
    private void HabilitarBotões(){
       btnEditar.setEnabled(true);
       btnExcluir.setEnabled(true);
    }
    private void HabilitarCampos(){
       txtID_enfermeiro.setEditable(true);
       txtNomeEnfermeiro.setEnabled(true);
       ComboEspecialização.setEnabled(true);
       txtEnfermeiroLogin.setEnabled(true);
       txtEnfermeirosenha.setEnabled(true);
       txtEnfermeiroEnde.setEnabled(true);
       txtEnfermeiroEmail.setEnabled(true);    
       txtEnfermeiroConfirmarSenha.setEnabled(true);
       ComboTipo.setEnabled(true);
    }
    
    public void preencherTabelaEnfermeiros(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Nome","Especialidade","Login","Email","Endereço","Tipo" };
        con.getConnection();
        con.executaSql(Sql);
        try {
            con.rs.first();
            do{                    
                  dados.add(new Object[]{con.rs.getInt("Id_enfermeiro"),con.rs.getString("nome"),con.rs.getString("especialização")
                  ,con.rs.getString("login"),con.rs.getString("email"),con.rs.getString("endereco"),con.rs.getString("tipo")});
                } while (con.rs.next());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Busque Novamente");
        }
         TabelaEnfermeiro tabelas = new TabelaEnfermeiro(dados, colunas);
         TabelaEnfermeiro.setModel(tabelas);
         TabelaEnfermeiro.getColumnModel().getColumn(0).setPreferredWidth(30);
         TabelaEnfermeiro.getColumnModel().getColumn(0).setResizable(true);
         TabelaEnfermeiro.getColumnModel().getColumn(1).setPreferredWidth(190);
         TabelaEnfermeiro.getColumnModel().getColumn(1).setResizable(true);
         TabelaEnfermeiro.getColumnModel().getColumn(2).setPreferredWidth(150);
         TabelaEnfermeiro.getColumnModel().getColumn(2).setResizable(true);
         TabelaEnfermeiro.getColumnModel().getColumn(3).setPreferredWidth(80);
         TabelaEnfermeiro.getColumnModel().getColumn(3).setResizable(true);
         TabelaEnfermeiro.getColumnModel().getColumn(4).setPreferredWidth(80);
         TabelaEnfermeiro.getColumnModel().getColumn(4).setResizable(true);
         TabelaEnfermeiro.getColumnModel().getColumn(5).setPreferredWidth(190);
         TabelaEnfermeiro.getColumnModel().getColumn(5).setResizable(true);
         TabelaEnfermeiro.getColumnModel().getColumn(6).setPreferredWidth(115);
         TabelaEnfermeiro.getColumnModel().getColumn(6).setResizable(true);
         TabelaEnfermeiro.getTableHeader().setReorderingAllowed(true);
         TabelaEnfermeiro.setAutoResizeMode(TabelaEnfermeiro.AUTO_RESIZE_OFF);
         TabelaEnfermeiro.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
         
         //con.desconecta();
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEnfermeiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadEnfermeiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEspecialização;
    private javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JTable TabelaEnfermeiro;
    private javax.swing.JButton btnBuscarEnfermeiro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtEnfermeiroConfirmarSenha;
    private javax.swing.JTextField txtEnfermeiroEmail;
    private javax.swing.JTextField txtEnfermeiroEnde;
    private javax.swing.JTextField txtEnfermeiroLogin;
    private javax.swing.JPasswordField txtEnfermeirosenha;
    private javax.swing.JTextField txtID_enfermeiro;
    private javax.swing.JTextField txtNomeEnfermeiro;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
