/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.bean.Medico;
import Tabelas.TabelaMedicos;
import model.conexao.Conexao;
import model.dao.MedicoDao;

/**
 *
 * @author mathe
 */
public class CadMedicos extends javax.swing.JFrame {

    Conexao con = new Conexao();
    Medico med = new Medico();
    MedicoDao control = new MedicoDao();
    int flag =0;
    
    
    public CadMedicos() {
        initComponents();
        con.getConnection();
        CamposInvisiveis();
        preencherTabelaMedicos("select * from medico order by nome");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnomemedico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcrm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboEspecializacao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtendereco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        txtpesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMedicos = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboPerfil = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        txtnomemedico.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("CRM:");

        txtcrm.setEnabled(false);
        txtcrm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcrmActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("ESPECIALIZAÇÃO:");

        comboEspecializacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "Cardiologia", "Dermatologia", "Ginecologia e Obstetrícia", "Ortopedia", "Anestesiologia" }));
        comboEspecializacao.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("LOGIN:");

        txtlogin.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("SENHA:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("EMAIL:");

        txtemail.setEnabled(false);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("ENDEREÇO:");

        txtendereco.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_pacientes.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save_37110.png"))); // NOI18N
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alter_pacientes.png"))); // NOI18N
        btnEditar.setToolTipText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_pacientes.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar_paciente.png"))); // NOI18N
        btncancelar.setToolTipText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/procurar.png"))); // NOI18N
        btnPesquisar.setToolTipText("Buscar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        TabelaMedicos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaMedicos);

        txtId.setEditable(false);
        txtId.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Perfil:");

        comboPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------", "Adminstrador", "Medico" }));
        comboPerfil.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Confirmar Senha:");

        txtsenha.setEnabled(false);

        txtConfirmarSenha.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtpesquisar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(btnPesquisar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtnomemedico, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcrm, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnomemedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("Cadastro de Medicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1132, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcrmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcrmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcrmActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtnomemedico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Nome para cadastrar:!");
            txtnomemedico.requestFocus();
        }else if (txtcrm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o CRM:!");
            txtcrm.requestFocus();
        }else if (txtlogin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Login:!");
            txtlogin.requestFocus();
        }else if (txtsenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a Senha:!");
            txtsenha.requestFocus();
        }else if (txtemail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Email:!");
            txtemail.requestFocus();
        }else if (txtendereco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Endereço:!");
            txtendereco.requestFocus();
        }else if(txtConfirmarSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Confirme sua senha:!");
            txtConfirmarSenha.requestFocus();
        }else if(txtsenha.getText().equals(txtConfirmarSenha.getText())){
            if(flag==1){
            med.setNome(txtnomemedico.getText());
            med.setEspecialização((String)comboEspecializacao.getSelectedItem());
            med.setCrm(Integer.parseInt(txtcrm.getText()));
            med.setLogin(txtlogin.getText());
            med.setSenha(txtsenha.getText());
            med.setEmail(txtemail.getText());
            med.setEndereco(txtendereco.getText());
            med.setTipo((String)comboPerfil.getSelectedItem());
            control.Salvar(med);
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja fazer mais alguma coisa?");
            if (resposta == JOptionPane.NO_OPTION) {
                dispose();
            }
            preencherTabelaMedicos("select * from medico order by nome");
            LimparCampos();
            DesabilitarBotões();
            DesabiliarCampos();
            btnNovo.setEnabled(true);
            }else{
            med.setID_medico((Integer.parseInt(txtId.getText())));
            med.setNome(txtnomemedico.getText());
            med.setEspecialização((String)comboEspecializacao.getSelectedItem());
            med.setCrm(Integer.parseInt(txtcrm.getText()));
            med.setLogin(txtlogin.getText());
            med.setSenha(txtsenha.getText());
            med.setEmail(txtemail.getText());
            med.setEndereco(txtendereco.getText());
            med.setTipo((String)comboPerfil.getSelectedItem());
            control.Editar(med);
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja fazer mais alguma coisa?");
            if (resposta == JOptionPane.NO_OPTION) { 
                dispose();
            }
            preencherTabelaMedicos("select * from medico order by nome");
            LimparCampos();
            DesabilitarBotões();
            DesabiliarCampos();
            btnNovo.setEnabled(true);
            }
        } else{
            JOptionPane.showMessageDialog(rootPane, "A senha que você digitou não confere!");
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed
  
    private void CamposInvisiveis(){
       txtId.setVisible(false);
    }
    
    private void DesabilitarBotões(){
       btnSalvar.setEnabled(false);
       btnEditar.setEnabled(false);
       btnExcluir.setEnabled(false);
       btncancelar.setEnabled(false);
    }
    private void DesabiliarCampos(){
       txtId.setEditable(false);
       txtnomemedico.setEnabled(false);
       txtcrm.setEnabled(false);
       comboEspecializacao.setEnabled(false);
       txtlogin.setEnabled(false);
       txtsenha.setEnabled(false);
       txtendereco.setEnabled(false);
       txtemail.setEnabled(false);    
       txtConfirmarSenha.setEnabled(false);
       comboPerfil.setEnabled(false);
    }
    private void LimparCampos() {
       txtId.setText("");
       txtnomemedico.setText("");
       txtcrm.setText("");
       comboEspecializacao.setSelectedItem("");
       txtlogin.setText("");
       txtsenha.setText("");
       txtendereco.setText("");
       txtemail.setText("");
       txtpesquisar.setText("");
       txtConfirmarSenha.setText("");
       comboPerfil.setSelectedItem("");
    }
    private void HabilitarBotões(){
       btnEditar.setEnabled(true);
       btnExcluir.setEnabled(true);
    }
    private void HabilitarCampos(){
    txtnomemedico.setEnabled(true);
    txtcrm.setEnabled(true);
    comboEspecializacao.setEnabled(true);
    txtlogin.setEnabled(true);
    txtsenha.setEnabled(true);
    txtendereco.setEnabled(true);
    txtemail.setEnabled(true);
    txtConfirmarSenha.setEnabled(true);
    comboPerfil.setEnabled(true);
    }
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag=1;
        btnSalvar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btncancelar.setEnabled(true);
        HabilitarCampos();
        LimparCampos();
        
    }//GEN-LAST:event_btnNovoActionPerformed
    
    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
       int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja cancelar?");
            if (resposta == JOptionPane.YES_OPTION) { 
                LimparCampos();
                DesabiliarCampos();
                DesabilitarBotões();
                btnNovo.setEnabled(true);
            }
        
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
      med.setPesquisa(txtpesquisar.getText());
      Medico model = control.buscarmedico(med);
      txtId.setText((String.valueOf(model.getID_medico())));
      txtnomemedico.setText(model.getNome());
      txtcrm.setText((String.valueOf(model.getCrm())));
      comboEspecializacao.setSelectedItem(model.getEspecialização());
      txtlogin.setText(model.getLogin());
      txtsenha.setText(model.getSenha());
      txtemail.setText(model.getEmail());
      txtendereco.setText(model.getEndereco());
      comboPerfil.setSelectedItem(model.getTipo());
      preencherTabelaMedicos("select * from medico where nome like '%"+med.getPesquisa()+"%'");
      btnEditar.setEnabled(true);
      
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        flag=2;
        HabilitarCampos();
        btnSalvar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            med.setID_medico(Integer.parseInt(txtId.getText()));
            control.Excluir(med);
            LimparCampos();
            DesabiliarCampos();
            DesabilitarBotões();
            btnNovo.setEnabled(true);
            preencherTabelaMedicos("select * from medico order by nome");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void TabelaMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMedicosMouseClicked
       String nome = ""+TabelaMedicos.getValueAt(TabelaMedicos.getSelectedRow(), 1);
       Conexao.getConnection();
       con.executaSql("select * from medico where nome='"+nome+"'");
        try {
            con.rs.first();
            txtId.setText(String.valueOf(con.rs.getInt("ID_medico")));
            txtnomemedico.setText(con.rs.getString("nome"));
            comboEspecializacao.setSelectedItem(con.rs.getString("especialização"));
            txtcrm.setText(String.valueOf(con.rs.getString("crm")));
            txtlogin.setText(con.rs.getString("login"));
            txtsenha.setText(con.rs.getString("senha"));
            txtConfirmarSenha.setText(con.rs.getString("senha"));
            txtemail.setText(con.rs.getString("email"));
            txtendereco.setText(con.rs.getString("endereco"));
            comboPerfil.setSelectedItem(con.rs.getString("tipo"));
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, "Erro no ao selecionar os dados"+ex);
         return;
        }
     //  con.desconecta();
     
        HabilitarBotões();
        
        
    }//GEN-LAST:event_TabelaMedicosMouseClicked
    
    public void preencherTabelaMedicos(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String[]{"ID","Nome","Especialidade","CRM","Login","Email","Endereço","Tipo" };
        con.getConnection();
        con.executaSql(Sql);
        try {
            con.rs.first();
            do{                    
                  dados.add(new Object[]{con.rs.getInt("Id_medico"),con.rs.getString("nome"),con.rs.getString("especialização"),con.rs.getInt("crm"),con.rs.getString("login"),
                      con.rs.getString("email"),con.rs.getString("endereco"),con.rs.getString("tipo")});
                } while (con.rs.next());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Busque Novamente");
        }
         TabelaMedicos tabela = new TabelaMedicos(dados, colunas);
         TabelaMedicos.setModel(tabela);
         TabelaMedicos.getColumnModel().getColumn(0).setPreferredWidth(30);
         TabelaMedicos.getColumnModel().getColumn(0).setResizable(true);
         TabelaMedicos.getColumnModel().getColumn(1).setPreferredWidth(190);
         TabelaMedicos.getColumnModel().getColumn(1).setResizable(true);
         TabelaMedicos.getColumnModel().getColumn(2).setPreferredWidth(150);
         TabelaMedicos.getColumnModel().getColumn(2).setResizable(true);
         TabelaMedicos.getColumnModel().getColumn(3).setPreferredWidth(80);
         TabelaMedicos.getColumnModel().getColumn(3).setResizable(true);
         TabelaMedicos.getColumnModel().getColumn(4).setPreferredWidth(80);
         TabelaMedicos.getColumnModel().getColumn(4).setResizable(true);
         TabelaMedicos.getColumnModel().getColumn(5).setPreferredWidth(190);
         TabelaMedicos.getColumnModel().getColumn(5).setResizable(true);
         TabelaMedicos.getColumnModel().getColumn(6).setPreferredWidth(115);
         TabelaMedicos.getColumnModel().getColumn(6).setResizable(true);
         TabelaMedicos.getColumnModel().getColumn(7).setPreferredWidth(115);
         TabelaMedicos.getColumnModel().getColumn(7).setResizable(true);
         TabelaMedicos.getTableHeader().setReorderingAllowed(true);
         TabelaMedicos.setAutoResizeMode(TabelaMedicos.AUTO_RESIZE_OFF);
         TabelaMedicos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         return;
         
       // con.desconecta();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaMedicos;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JComboBox<String> comboEspecializacao;
    private javax.swing.JComboBox<String> comboPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtcrm;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtnomemedico;
    private javax.swing.JTextField txtpesquisar;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
  
}
