/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.bean.Hora;
import model.conexao.Conexao;
 

/**
 *
 * @author mathe
 */
public class Home extends javax.swing.JFrame {
    
  
    Conexao con = new Conexao();
    CadMedicos tela = new CadMedicos();
    CadEnfermeiros telaenfermeiro = new CadEnfermeiros();
    TelaPaciente telapac = new TelaPaciente();
    Agendamento agendamento = new Agendamento();
    
    public Home(String usuário) {
        initComponents();
        Connection connection;
        connection = Conexao.getConnection();
        
        lbusuarios.setText(usuário);
     
        
        
        // A  linha Abaixo exibe a Data Atual do Sistema.
        Date data = new Date();
        DateFormat formatadorD = DateFormat.getDateInstance(DateFormat.LONG);
        CampoData.setText(formatadorD.format(data));
        
        // A linha Abaixo exibe a Hora Atual do Sistema.
        Hora mostra_hora = new Hora();
        mostra_hora.ler_hora();
        campohora.setText("Hora Atual: " + mostra_hora.hora);
        
        timer1.start();
       
        //Esse método seta a Imagem no nosso label referente ao DB
        if (con != null) {
            lbdb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banco.png")));
        }else{
            lbdb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banco2.png")));
        }
    }
    

    private Home() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jInternalFrameprincipal = new javax.swing.JInternalFrame();
        jPanelinternalframe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCadastroMedicos = new javax.swing.JButton();
        btnCadastroEnfermeiros = new javax.swing.JButton();
        btnCadastroPacientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAgenda = new javax.swing.JButton();
        btnSairFrame = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbusuarios = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoData = new javax.swing.JLabel();
        campohora = new javax.swing.JLabel();
        lbdb = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        subCadEnfermeiros = new javax.swing.JMenu();
        subCadMedicos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        subCadPacientes = new javax.swing.JMenuItem();
        subCadUsuarios = new javax.swing.JMenuItem();
        menuFerramenta = new javax.swing.JMenu();
        subFerramenta = new javax.swing.JMenuItem();
        MenuRelatórios = new javax.swing.JMenu();
        subpacientes = new javax.swing.JMenuItem();
        subMedicos = new javax.swing.JMenuItem();
        subConsultas = new javax.swing.JMenuItem();
        subEnfermeiros = new javax.swing.JMenuItem();
        subAgendamento = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menusair = new javax.swing.JMenu();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrameprincipal.setTitle("Bem-Vindo");
        jInternalFrameprincipal.setVisible(true);
        jInternalFrameprincipal.getContentPane().setLayout(null);

        jPanelinternalframe.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Cadastros - ");
        jPanelinternalframe.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 17);

        btnCadastroMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CadMedicos.png"))); // NOI18N
        btnCadastroMedicos.setToolTipText("Médicos");
        btnCadastroMedicos.setAutoscrolls(true);
        btnCadastroMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroMedicosActionPerformed(evt);
            }
        });
        jPanelinternalframe.add(btnCadastroMedicos);
        btnCadastroMedicos.setBounds(10, 30, 107, 120);

        btnCadastroEnfermeiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon-infermeira.png"))); // NOI18N
        btnCadastroEnfermeiros.setToolTipText("Enfermeiro");
        btnCadastroEnfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroEnfermeirosActionPerformed(evt);
            }
        });
        jPanelinternalframe.add(btnCadastroEnfermeiros);
        btnCadastroEnfermeiros.setBounds(119, 30, 120, 120);

        btnCadastroPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadPacientes.png"))); // NOI18N
        btnCadastroPacientes.setToolTipText("Paciente");
        btnCadastroPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPacientesActionPerformed(evt);
            }
        });
        jPanelinternalframe.add(btnCadastroPacientes);
        btnCadastroPacientes.setBounds(240, 30, 110, 120);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Agendamento do Dia");
        jPanelinternalframe.add(jLabel1);
        jLabel1.setBounds(170, 190, 160, 17);

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agenda.png"))); // NOI18N
        btnAgenda.setToolTipText("Agenda");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        jPanelinternalframe.add(btnAgenda);
        btnAgenda.setBounds(10, 216, 110, 117);

        btnSairFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnSairFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairFrameActionPerformed(evt);
            }
        });
        jPanelinternalframe.add(btnSairFrame);
        btnSairFrame.setBounds(970, 0, 40, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Agendamentos");
        jPanelinternalframe.add(jLabel5);
        jLabel5.setBounds(10, 190, 120, 17);

        jButton1.setText("jButton1");
        jPanelinternalframe.add(jButton1);
        jButton1.setBounds(170, 216, 120, 117);

        jInternalFrameprincipal.getContentPane().add(jPanelinternalframe);
        jPanelinternalframe.setBounds(10, 20, 1010, 350);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuarios.png"))); // NOI18N
        jLabel3.setText("Usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbdb, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(CampoData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campohora, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFrameprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jInternalFrameprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lbusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbdb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CampoData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campohora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arquivo.png"))); // NOI18N
        jMenu2.setToolTipText("Arquivo");

        jMenuItem5.setText("Medicamentos e fórmulas");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Procedimentos e exames");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Biblioteca");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Convênios");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Cadastro de doenças");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        subCadEnfermeiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add_new_user_16686.png"))); // NOI18N
        subCadEnfermeiros.setToolTipText("Cadastros");

        subCadMedicos.setText("Médicos");
        subCadMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCadMedicosActionPerformed(evt);
            }
        });
        subCadEnfermeiros.add(subCadMedicos);

        jMenuItem3.setText("Enfermeiros");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        subCadEnfermeiros.add(jMenuItem3);

        subCadPacientes.setText("Pacientes");
        subCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCadPacientesActionPerformed(evt);
            }
        });
        subCadEnfermeiros.add(subCadPacientes);

        subCadUsuarios.setText("Usuarios");
        subCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCadUsuariosActionPerformed(evt);
            }
        });
        subCadEnfermeiros.add(subCadUsuarios);

        jMenuBar1.add(subCadEnfermeiros);

        menuFerramenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ferramenta.png"))); // NOI18N
        menuFerramenta.setToolTipText("Ferramenta");

        subFerramenta.setText("Bem-Vindo");
        subFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subFerramentaActionPerformed(evt);
            }
        });
        menuFerramenta.add(subFerramenta);

        jMenuBar1.add(menuFerramenta);

        MenuRelatórios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impressora.png"))); // NOI18N
        MenuRelatórios.setToolTipText("Impressões");
        MenuRelatórios.setBorderPainted(true);
        MenuRelatórios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        subpacientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        subpacientes.setText("Pacientes");
        subpacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subpacientesActionPerformed(evt);
            }
        });
        MenuRelatórios.add(subpacientes);

        subMedicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        subMedicos.setText("Médicos");
        subMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMedicosActionPerformed(evt);
            }
        });
        MenuRelatórios.add(subMedicos);

        subConsultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        subConsultas.setText("Consultas");
        MenuRelatórios.add(subConsultas);

        subEnfermeiros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        subEnfermeiros.setText("Enfermeiros");
        subEnfermeiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subEnfermeirosActionPerformed(evt);
            }
        });
        MenuRelatórios.add(subEnfermeiros);

        subAgendamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        subAgendamento.setText("Agendamentos");
        subAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subAgendamentoActionPerformed(evt);
            }
        });
        MenuRelatórios.add(subAgendamento);

        jMenuItem10.setText("Ficha do paciente");
        MenuRelatórios.add(jMenuItem10);

        jMenuItem11.setText("Atestado");
        MenuRelatórios.add(jMenuItem11);

        jMenuItem12.setText("Declaração");
        MenuRelatórios.add(jMenuItem12);

        jMenuItem13.setText("Fatura para convênios");
        MenuRelatórios.add(jMenuItem13);

        jMenuItem14.setText("Relação de pacientes");
        MenuRelatórios.add(jMenuItem14);

        jMenuBar1.add(MenuRelatórios);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agenda2.png"))); // NOI18N
        jMenu1.setToolTipText("Agenda");
        jMenu1.setAutoscrolls(true);
        jMenu1.setBorderPainted(true);

        jMenuItem1.setText("Agendamentos do dia");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agenda Medico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-mapping256_24899.png"))); // NOI18N
        jMenu3.setToolTipText("Trocar de Usuário");
        jMenu3.setAutoscrolls(true);
        jMenu3.setBorderPainted(true);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        menusair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout256_24927.png"))); // NOI18N
        menusair.setToolTipText("Sair");
        menusair.setAutoscrolls(true);
        menusair.setBorderPainted(true);
        menusair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menusairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menusair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1116, 686));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void subMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subMedicosActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void subCadMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCadMedicosActionPerformed
      
        try {
            con.executaSql("select*from medico where login='"+lbusuarios.getText()+"'");
            con.rs.first();
            if (con.rs.getString("tipo").equals("Medico")) {
                if (tela==null) {
                    tela = new CadMedicos();
                    tela.setVisible(true);
                    tela.setResizable(false);
                }else{
                    tela.setVisible(true);
                    tela.setResizable(false);
                }
               // CadMedicos cadastroMed = new CadMedicos();
               //cadastroMed.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!"+ex.getMessage());
         }
    }//GEN-LAST:event_subCadMedicosActionPerformed

    private void btnCadastroMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroMedicosActionPerformed
       try {
            con.executaSql("select*from medico where login='"+lbusuarios.getText()+"'");
            con.rs.first();
            if (con.rs.getString("tipo").equals("Medico")) {
               if (tela==null) {
                    tela = new CadMedicos();
                    tela.setVisible(true);
                    tela.setResizable(false);
                }else{
                    tela.setVisible(true);
                    tela.setResizable(false);
                }
                //CadMedicos cadastroMed = new CadMedicos();
                //cadastroMed.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!"+ex.getMessage());
         }
    }//GEN-LAST:event_btnCadastroMedicosActionPerformed

    private void subFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subFerramentaActionPerformed
       jInternalFrameprincipal.setVisible(true);
    }//GEN-LAST:event_subFerramentaActionPerformed

    private void btnSairFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairFrameActionPerformed
       jInternalFrameprincipal.dispose();
    }//GEN-LAST:event_btnSairFrameActionPerformed

    private void menusairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menusairMouseClicked
       System.exit(0);
       con.desconecta();
    }//GEN-LAST:event_menusairMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
       TelaLogin Telas = new TelaLogin();
       Telas.setVisible(true);
       dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void subCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCadUsuariosActionPerformed
       
    }//GEN-LAST:event_subCadUsuariosActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       try {
            con.executaSql("select * from enfermeiro where login='"+lbusuarios.getText()+"'");
            con.rs.first();
            if (con.rs.getString("tipo").equals("Enfermeiro")) {
                if (telaenfermeiro==null) {
                    telaenfermeiro = new CadEnfermeiros();
                    telaenfermeiro.setVisible(true);
                    telaenfermeiro.setResizable(false);
                }else{
                    telaenfermeiro.setVisible(true);
                    telaenfermeiro.setResizable(false);
                }
                //CadEnfermeiros enfermeiro = new CadEnfermeiros();
                //enfermeiro.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!"+ex.getMessage());
         }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnCadastroEnfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroEnfermeirosActionPerformed
      try {
            con.executaSql("select*from enfermeiro where login='"+lbusuarios.getText()+"'");
            con.rs.first();
            if (con.rs.getString("tipo").equals("Enfermeiro")) {
               if (telaenfermeiro==null) {
                    telaenfermeiro = new CadEnfermeiros();
                    telaenfermeiro.setVisible(true);
                    telaenfermeiro.setResizable(false);
                }else{
                    telaenfermeiro.setVisible(true);
                    telaenfermeiro.setResizable(false);
                }
                //CadEnfermeiros enfermeiro = new CadEnfermeiros();
                //enfermeiro.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!"+ex.getMessage());
         }
    }//GEN-LAST:event_btnCadastroEnfermeirosActionPerformed

    private void btnCadastroPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPacientesActionPerformed
       try {
            con.executaSql("select*from enfermeiro where login='"+lbusuarios.getText()+"'");
            con.rs.first();
            if (con.rs.getString("tipo").equals("Supervisor")) {
               if (telapac==null) {
                    telapac = new TelaPaciente();
                    telapac.setVisible(true);
                    telapac.setResizable(false);
                }else{
                    telapac.setVisible(true);
                    telapac.setResizable(false);
                }
                //CadEnfermeiros enfermeiro = new CadEnfermeiros();
                //enfermeiro.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!"+ex.getMessage());
         }
    }//GEN-LAST:event_btnCadastroPacientesActionPerformed

    private void subCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCadPacientesActionPerformed
        try {
            con.executaSql("select * from enfermeiro where login='"+lbusuarios.getText()+"'");
            con.rs.first();
            if (con.rs.getString("tipo").equals("Supervisor")) {
               if (telapac==null) {
                    telapac = new TelaPaciente();
                    telapac.setVisible(true);
                    telapac.setResizable(false);
                }else{
                    telapac.setVisible(true);
                    telapac.setResizable(false);
                }
                //CadEnfermeiros enfermeiro = new CadEnfermeiros();
                //enfermeiro.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!"+ex.getMessage());
         }
    }//GEN-LAST:event_subCadPacientesActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
      try {
            con.executaSql("select*from medico where login='"+lbusuarios.getText()+"'");
            con.rs.first();
            if (con.rs.getString("tipo").equals("Medico")) {
               if (telapac==null) {
                    agendamento = new Agendamento();
                    agendamento.setVisible(true);
                    agendamento.setResizable(false);
                }else{
                    agendamento.setVisible(true);
                    agendamento.setResizable(false);
                }
                //CadEnfermeiros enfermeiro = new CadEnfermeiros();
                //enfermeiro.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem Acesso a essa Funcionalidade!\n Contate o Administrador do Sistema!"+ex.getMessage());
         }
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
       Agenda telaagenda = new Agenda();
       telaagenda.setVisible(true);
       
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AgendaMedico agendamedico = new AgendaMedico();
        agendamedico.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void subpacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subpacientesActionPerformed
      Connection com = Conexao.getConnection();
       //metodo de chamada da nosso Relatorio Pacientes
      /* int confirma = JOptionPane.showConfirmDialog(null, "Confirmar impressão?", "Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma==JOptionPane.YES_OPTION) {
            //Impressão de Relatório
            String src = "C:/Users/Vaio/Desktop/Controle_de_Gastos/Clinica/Relatorio Pacientes/Relatorio de Paciente.jasper";
            JasperPrint jasperPrint = null;
        try { 
            
            jasperPrint = JasperFillManager.fillReport(src, null, com);
            
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Gerar o Relatório! \n"+e);
        }
        JasperViewer view = new JasperViewer(jasperPrint,false);
            view.setVisible(true);
        }*/
       
    }//GEN-LAST:event_subpacientesActionPerformed

    private void subEnfermeirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subEnfermeirosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subEnfermeirosActionPerformed

    private void subAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subAgendamentoActionPerformed
        //
        Connection com = Conexao.getConnection();
       //metodo de chamada da nosso Relatorio Pacientes
      /* int confirma = JOptionPane.showConfirmDialog(null, "Confirmar impressão?", "Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma==JOptionPane.YES_OPTION) {
            //Impressão de Relatório
            String src = "C:/Users/Vaio/Desktop/Controle_de_Gastos/Clinica/Relatorio Pacientes/Relatorios Diarios.jasper";
            JasperPrint jasperPrint = null;
        try { 
            
            jasperPrint = JasperFillManager.fillReport(src, null, com);
            
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Gerar o Relatório! \n"+e);
        }
        JasperViewer view = new JasperViewer(jasperPrint,false);
            view.setVisible(true);
        }*/
    }//GEN-LAST:event_subAgendamentoActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        //Thread que atualiza o horário
        // A linha Abaixo exibe a Hora Atual do Sistema.
            Hora mostra_hora = new Hora();
            mostra_hora.ler_hora();
            campohora.setText("Hora Atual:" + mostra_hora.hora);        // TODO add your handling code here:
    }//GEN-LAST:event_timer1OnTime

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CampoData;
    private javax.swing.JMenu MenuRelatórios;
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnCadastroEnfermeiros;
    private javax.swing.JButton btnCadastroMedicos;
    private javax.swing.JButton btnCadastroPacientes;
    private javax.swing.JToggleButton btnSairFrame;
    private javax.swing.JLabel campohora;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrameprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelinternalframe;
    private javax.swing.JLabel lbdb;
    private javax.swing.JLabel lbusuarios;
    private javax.swing.JMenu menuFerramenta;
    private javax.swing.JMenu menusair;
    private javax.swing.JMenuItem subAgendamento;
    private javax.swing.JMenu subCadEnfermeiros;
    private javax.swing.JMenuItem subCadMedicos;
    private javax.swing.JMenuItem subCadPacientes;
    private javax.swing.JMenuItem subCadUsuarios;
    private javax.swing.JMenuItem subConsultas;
    private javax.swing.JMenuItem subEnfermeiros;
    private javax.swing.JMenuItem subFerramenta;
    private javax.swing.JMenuItem subMedicos;
    private javax.swing.JMenuItem subpacientes;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
